apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organizations.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              properties:
                datasources:
                  description: Grafana datasources
                  type: array
                  items:
                    type: object
                    required: [name, data]
                    properties:
                      name:
                        type: string
                      data:
                        type: string
                dashboards:
                  description: Grafana dashboards
                  type: array
                  items:
                    type: object
                    required: [name, data]
                    properties:
                      name:
                        type: string
                      data:
                        type: string
      additionalPrinterColumns:
      - jsonPath: .spec.datasources[*].name
        name: Datasources
        type: string
      - jsonPath: .spec.dashboards[*].name
        name: Dashboards
        type: string
  names:
    kind: Organization
    plural: organizations
    singular: organization
    shortNames:
      - orgs
      - org
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: [email]
              properties:
                email:
                  description: User's email to access Grafana
                  type: string
                organizations:
                  description: Organizations where the user belongs
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
      - jsonPath: .spec.email
        name: Email
        type: string
      - jsonPath: .spec.organizations
        name: Organizations
        type: string
  names:
    kind: User
    plural: users
    singular: user
    shortNames:
      - users
      - user
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dashboards.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: [dashboard, organizations]
              properties:
                dashboard:
                  type: object
                  description: Grafana Dashboard in JSON format
                  required: [name, data]
                  properties:
                    name:
                      type: string
                    title:
                      type: string
                    data:
                      type: string
                organizations:
                  description: Grafana Organizations the dashboard belongs to
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
      - jsonPath: .spec.organizations
        name: Organizations
        type: string
  names:
    kind: Dashboard
    plural: dashboards
    singular: dashboard
    shortNames:
      - dash
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datasources.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: [datasource, organizations]
              properties:
                datasource:
                  type: object
                  description: Grafana datasource in JSON format
                  required: [name, data]
                  properties:
                    name:
                      type: string
                    data:
                      type: string
                organizations:
                  description: Grafana Organizations the dashboard belongs to
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
      - jsonPath: .spec.organizations
        name: Organizations
        type: string
  names:
    kind: Datasource
    plural: datasources
    singular: datasource
    shortNames:
      - dts